### ISSUE TITLE
png 파일을 import하는데 에러가 납니다.

### ISSUE THREAD

**Issue by newtypeid** [MM-MockUp-Maker/mockup-maker#3]
file : src/components/header/index.tsx
line : 2 
branch : feature/draw-layout

**Comment by inyong-e** [comment]
## Caustion

### this code
```
import * as React from 'react';
import logo from '../../assets/logo.png'; //  <--- 'can not find module...'

import './header.scss';
export const HeaderComponent = () => (
  <div className="header_container">
    <div className="header_inner">
      <img src={logo} alt="" />
      <h2>Mockup Maker</h2>
    </div>
  </div>
);
```

타입스크립트에서 import로 파일을 찾을 때, **ts,tsx 파일만 찾도록 기본 설정**이 되어 있어서 그런 것 같아요.
그래서 해당 경로에 png 파일이 있어도 추적할 파일 대상에서 이미 제외되었기 때문에 못 찾는 듯 합니다.
(추적만 안되는거지 파일이 실제로 없는 것은 아니므로, 번들링 후 프로젝트 실행할 때는 정상적으로 되는 것이지요.)

 
### 💡 Q&A
**_Q: SCSS파일은 왜 그런 에러가 나지 않는 건가요?_**
**A: 'import 변수명 from' 말고, 그냥 'import from' 파일은 참조하도록 가리키는 파일 대상일 뿐, 직접 가져와서 사용하는 파일대상이 아니므로 import from 선언에는 따로 파일 대상을 추적하지 않는 듯 함. 대신 번들링 시에는 대상이 잘못 되어있으면 문제는 생기겠죠? 근데 요건 뇌피셜이라 따로 한 번 찾아보시면 좋을 듯.**

### suggest resolution
png 파일로 대상으로 넣어주려면 .d.ts 라고 따로 설정파일을 만들어 줘야 하나봐요. (요건 저도 첨 봄..)
여기서 png파일도 import로 불러올 추적파일 대상으로 설정해주면 됩니다.
**ref** : https://stackoverflow.com/questions/57127606/ts2307-cannot-find-module-images-logo-png

---

### (+Add suggestion)

png 파일을 import해서 불러오면 컴파일 할 때마다 png 파일도 포함해서 번들링을 하게 되서, 만약 이미지 경로가 잘못되거나 자체에 문제(깨진 이미지 파일 등)가 있으면 웹팩 컴파일이 일어나게되서 **프로젝트 전체가 먹통이 되는 문제**가 있을 것 같아요.

이미지 파일은 프로젝트 내 경로만 잡아주면 알아서 임포트가 되므로, 따로 **상수를 이용해서 이미지 경로만 지정**해주면 될 것 같은데 어떠신가요? 

**Suggest Code**

```
import * as React from 'react';
import './header.scss';

const LOGO_PATH = './src/assets/logo.png'; //  <--- this!

export const HeaderComponent = () => (
  <div className="header_container">
    <div className="header_inner">
      <img src={LOGO_PATH} alt="" />
      <h2>Mockup Maker</h2>
    </div>
  </div>
);
```
이렇게 하면 해당 이미지 경로가 틀렸거나, 깨진 파일이여도 프로젝트 자체는 영향이 가지 않으므로 조금 더 안정적일 것 같아요.

요건 @newtypeid 님께서 알아서 판단해주시면 될 듯!

**Comment by newtypeid** [comment]
+Add Suggestion에 나온 경로를 const로 지정해서 쓰는 방법은 완전하진 않은 방법인 것 같습니다.

1. 상대경로를 인지하지 못합니다 . ex) ../../assets/logo.png
2. 절대경로는 인지합니다. ex) src/assets/logo.png
